spring:  
  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: jdbc:h2:mem:wiam0;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
 port: 8083
